version: '3.7'

networks:
  app-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    env_file:
      - ./backend.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    image: 'bitnami/redis:latest'
    networks:
      - app-network
    ports:
      - 6379:6379
    env_file:
      - ./backend.env

  api_server:
    build: backend
    env_file:
      - ./backend.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/backend:/app/backend
      - ./backend/manage.py:/app/manage.py

  ui:
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend.local.env
    depends_on:
      - api_server
    ports:
      - 3000:3000
    volumes:
      - ./ui/public:/web/app/public
      - ./ui/src:/web/app/src

  nginx:
    build: nginx
    depends_on:
      - api_server
      - ui
    ports:
      - 80:80

volumes:
  mongodb_data_container: